/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package org.apache.hadoop.fs.azurebfs.extensions

//import org.scalatest.funsuite.AnyFunSuite
//import org.junit.runner.RunWith
//import org.scalatestplus.junit.JUnitRunner
/*
@RunWith(classOf[JUnitRunner])
class LibrarySuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new datalakeSASTokenProvider()
    //assert(library.init())
  }
}
*/